---
- name: install rabbitmq
  sudo: yes
  package:
    name: rabbitmq-server
    state: present

- name: ensure rabbitmq is running and enabled
  sudo: yes
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
